# Generated by Django 4.1.5 on 2023-01-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='actors',
            new_name='actor',
        ),
    ]
