# Generated by Django 4.1.5 on 2023-01-11 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0002_rename_actors_movies_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imdb_app.producer'),
        ),
    ]
