# Generated by Django 4.1.5 on 2023-01-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0003_alter_movies_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
