# Generated by Django 4.1.5 on 2023-01-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0004_alter_movies_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='poster',
        ),
    ]
