# Generated by Django 4.1.5 on 2023-01-18 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0005_remove_movies_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb_app.producer'),
        ),
    ]
