# Generated by Django 4.1.5 on 2023-01-19 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0006_alter_movies_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='plot',
            field=models.CharField(default='It is an historical movie about the queen padmavati and the invader allaudin khilji', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movies',
            name='actor',
            field=models.ManyToManyField(blank=True, to='imdb_app.actors'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imdb_app.producer'),
        ),
    ]
